import Head from "next/head";
import { Roboto } from "next/font/google";
import "@fontsource/public-sans";
import HomePage from "../components/Homepage";
import {getAuth, onAuthStateChanged } from "firebase/auth";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function index() {
  // const auth = getAuth();
  // onAuthStateChanged(auth, (user) => {
  //   if (user) {
  //     // User is signed in, set currentUser
  //   } else {
  //     // User is signed out, clear currentUser
  //   }
  //   // Unsubscribe from onAuthStateChanged listener when component unmounts
  //   return;
  // });

  return (
    <>
      <Head>
        <title>FridayFinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage></HomePage>
      </main>
    </>
  );
}
