import Head from "next/head";
import { Roboto } from "next/font/google";
import "@fontsource/public-sans";
import Login from "./Login";
import App from "./firebase";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { useState } from "react";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

// Firebase Authentication
const auth = getAuth(App);

export default function Home() {
  const [user, setUser] = useState(null);

  // detect auth state changes
  onAuthStateChanged(auth, (userLoggedIn) => {
    if (userLoggedIn) {
      console.log("Logged in");
      setUser(user);
    } else {
      console.log("No User");
    }
  });

  return (
    <>
      <Head>
        <title>FridayFinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          user ?
          <h3>Authenticated</h3>
          :
          <Login></Login>
        }
      </main>
    </>
  );
}
